name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Mod
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Geode SDK
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: nightly
          # Eliminamos la l√≠nea de bindings para que use los de defecto.
          # Esto arregla el error "Invalid repository".

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyCustomMod
          path: build/*.geode
